feat: update build.yml from secureblue example

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,40 +1,143 @@
-name: bluebuild
+
+# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
+#
+# SPDX-License-Identifier: Apache-2.0
+name: build
+
+permissions: {}
+
 on:
   schedule:
-    - cron: "00 6 * * *" # build at 06:00 UTC every day 
+    - cron:
+        "00 08 * * *"
   push:
-    paths-ignore: # don't rebuild if only documentation has changed
+    paths-ignore: 
       - "**.md"
-  pull_request:
-  workflow_dispatch: # allow manually triggering builds
+
+  workflow_dispatch:
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
+  cancel-in-progress: true
+
 jobs:
-  bluebuild:
-    name: Build Custom Image
-    runs-on: ubuntu-latest
+  build:
+    name: Build
+    runs-on: ubuntu-24.04
     outputs:
-      FULL_IMAGE_REF: ${{ steps.runner_setup.outputs.FULL_IMAGE_REF }}
+      FULL_IMAGE_REF: ${{ steps.image_data.outputs.FULL_IMAGE_REF }}
       IMAGE_DIGEST: ${{ steps.image_manifest_metadata.outputs.IMAGE_DIGEST }}
     permissions:
-      contents: read # Needed to pull the repo for the build
-      actions: read # Needed to read actions and actions logs for provenance generation
-      packages: write # Needed to publish images
-      id-token: write # Needed for token generation for signing
+      contents: read
+      packages: write
+      id-token: write
     strategy:
-      fail-fast: false # Stops GitHub from cancelling all matrix builds if one fails
+      fail-fast: false 
       matrix:
         recipe:
           - startingleaf.yml
-          # - startingleaf-sway.yml
     steps:
-       # the build is fully handled by the reusable github action
-      - name: Build Startingleaf 
-        uses: blue-build/github-action@v1.11.0
+      - name: Checkout repo
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
         with:
+          persist-credentials: false
+
+      - name: Optimize build times
+        shell: bash
+        run: |
+          echo 'set man-db/auto-update false' | sudo debconf-communicate
+          sudo dpkg-reconfigure man-db
+          sudo rm -f /var/lib/man-db/auto-update
+          sudo sed -i 's/^update_initramfs=.*/update_initramfs=no/' /etc/initramfs-tools/update-initramfs.conf
+
+      - name: Drop Ubuntu HTTP mirrors
+        shell: bash
+        run: |
+          sudo sed -i '/^http:\/\//d' /etc/apt/apt-mirrors.txt
+          sudo apt-get update
+
+      - name: Install dependencies
+        shell: bash
+        run: |
+          sudo apt install yq
+
+      - name: Gather image data from recipe
+        id: image_data
+        shell: bash
+        env:
+          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
+          PR_EVENT_NUMBER: ${{ github.event.number }}
+          RECIPE: ${{ matrix.recipe }}
+        run: |
+          IMAGE_NAME=$(yq -r '."name"' "./recipes/${RECIPE}")
+          echo "IMAGE_NAME=${IMAGE_NAME}" >> "${GITHUB_OUTPUT}"
+          echo "BASE_IMAGE=$(yq -r '."base-image"' "./recipes/${RECIPE}")" >> "${GITHUB_OUTPUT}"
+          echo "BASE_IMAGE_VERSION=$(yq -r '."image-version"' "./recipes/${RECIPE}")" >> "${GITHUB_OUTPUT}"
+
+          FULL_IMAGE_REF="ghcr.io/oakleafknight06/startingleaf:latest"
+          echo "FULL_IMAGE_REF=${FULL_IMAGE_REF}" >> "${GITHUB_OUTPUT}"
+
+      - name: Install slsa-verifier
+        uses: slsa-framework/slsa-verifier/actions/installer@ea584f4502babc6f60d9bc799dbbb13c1caa9ee6 # v2.7.1
+
+      - name: Verify base image provenance
+        shell: bash
+        env:
+          BASE_IMAGE_VERSION: ${{ steps.image_data.outputs.BASE_IMAGE_VERSION }}
+          BASE_IMAGE: ${{ steps.image_data.outputs.BASE_IMAGE }}
+        run: |
+          # Install crane
+          CRANE_VERSION=v0.20.7
+          CRANE_OS=Linux
+          CRANE_ARCH=x86_64
+            curl -fLsS --retry 5 \
+              -o 'go-containerregistry.tar.gz' "https://github.com/google/go-containerregistry/releases/download/${CRANE_VERSION}/go-containerregistry_${CRANE_OS}_${CRANE_ARCH}.tar.gz" \
+              -o 'provenance.intoto.jsonl' "https://github.com/google/go-containerregistry/releases/download/${CRANE_VERSION}/multiple.intoto.jsonl"
+          slsa-verifier verify-artifact go-containerregistry.tar.gz --provenance-path provenance.intoto.jsonl --source-uri github.com/google/go-containerregistry --source-tag "${CRANE_VERSION}"
+          tar -zxvf go-containerregistry.tar.gz -C /usr/local/bin/ crane
+
+          DIGEST=$(crane digest "${BASE_IMAGE}:${BASE_IMAGE_VERSION}")
+          slsa-verifier verify-image --source-uri 'github.com/secureblue/secureblue' "${BASE_IMAGE}:${BASE_IMAGE_VERSION}@${DIGEST}"
+
+      - name: Uninstall slsa-verifier
+        shell: bash
+        run: |
+          # remove slsa-verifier so that it can be successfully reinstalled later by bluebuild
+          rm -rf ~/.slsa/
+
+      - name: Install cosign
+        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
+        with:
+          cosign-release: 'v2.6.0'
+
+      - name: Verify base image
+        shell: bash
+        env:
+          BASE_IMAGE_VERSION: ${{ steps.image_data.outputs.BASE_IMAGE_VERSION }}
+          BASE_IMAGE: ${{ steps.image_data.outputs.BASE_IMAGE }}
+        run: |
+          UPSTREAM_CONTAINER="${BASE_IMAGE}:${BASE_IMAGE_VERSION}"
+          UPSTREAM_PUBKEY='./files/system/etc/pki/containers/secureblue.pub'
+          if ! cosign verify --key "${UPSTREAM_PUBKEY}" "${UPSTREAM_CONTAINER}" | jq; then
+            echo "NOTICE: Verification failed. Please ensure your public key is correct."
+            exit 1
+          fi
+
+      - name: Build image
+        uses: blue-build/github-action@3cd0c2835e691b87a7eb19261a6aee77a56169e2 # v1.11.0
+        env:
+          KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}
+        with:
+          cli_version: v0.9.32
           recipe: ${{ matrix.recipe }}
           cosign_private_key: ${{ secrets.SIGNING_SECRET }}
           registry_token: ${{ github.token }}
           pr_event_number: ${{ github.event.number }}
-          build_chunked_oci: true
+          squash: true
+          skip_checkout: true
+          use_cache: false
+          retry_push_count: 3
+          verify_install: true
 
       - name: Install regctl
         uses: regclient/actions/regctl-installer@1b705e32d40851370799ea5814e83d0a5f6a70dc # v0.1.0
@@ -42,12 +145,14 @@ jobs:
       - name: Parse image manifest
         id: image_manifest_metadata
         shell: bash
+        env:
+          FULL_IMAGE_REF: ${{ steps.image_data.outputs.FULL_IMAGE_REF }}
         run: |
-          IMAGE_DIGEST=$(regctl image digest "ghcr.io/oakleafknight06/startingleaf:latest")
+          IMAGE_DIGEST=$(regctl image digest "${FULL_IMAGE_REF}")
           echo "IMAGE_DIGEST=${IMAGE_DIGEST}" >> "${GITHUB_OUTPUT}"
 
   provenance:
-    needs: [bluebuild]
+    needs: [build]
     permissions:
       actions: read # for detecting the Github Actions environment.
       id-token: write # for creating OIDC tokens for signing.
@@ -56,8 +161,8 @@ jobs:
     # https://github.com/slsa-framework/slsa-github-generator?tab=readme-ov-file#referencing-slsa-builders-and-generators
     uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
     with:
-      image: ${{ needs.bluebuild.outputs.FULL_IMAGE_REF }}
-      digest: ${{ needs.bluebuild.outputs.IMAGE_DIGEST }}
+      image: ${{ needs.uil.outputs.FULL_IMAGE_REF }}
+      digest: ${{ needs.uil.outputs.IMAGE_DIGEST }}
       registry-username: ${{ github.actor }}
     secrets:
       registry-password: ${{ secrets.GITHUB_TOKEN }}
